%
% 2011/08/25
% realTimeDemo2ndTraining.m makes joint vectors for 2nd GMM training
%
% NOTES
% joint vectors for GMM training:
%   preparation: vowels
%   1st: vowels + consonants obtained by S2H
%   2nd: vowels + consonants generated by 1st model/recorded again 
%
% AUTHOR
% Aki Kunikoshi (D3)
% yemaozi88@gmail.com
%

clear all, fclose all, clc;
vowel = ['a', 'i', 'u', 'e', 'o'];
consonant = ['m', 'n', 'r'];
%transition = ['c', 'm'];

firstPhoneme = [vowel, consonant];

% 0: using generated data
% 1: using recorded data
TYPE = 1;


%% using generated data
if TYPE == 0
    generatedConsonantsDir = 'F:\H2SwithDelta\2ndTrain_byGeneratedData\generatedConsonantsDgv';
    dirSc = 'F:\JapaneseConsonants';
    dirJoint = 'F:\H2SwithDelta\2ndTrain_byGeneratedData\jointHS_consonants';

    logfile = [dirJoint '\frameNum_jointHS_consonants.txt'];
    flog = fopen(logfile, 'wt');
    
    for nFP = 6:8 % the first phoneme
        for nV2 = 1:5 % the vowel follows the first phoneme
            mora = [firstPhoneme(nFP) vowel(nV2)];
            fS = [dirSc '\' firstPhoneme(nFP) '\suzuki\16k\scep18\1\' mora '.scep'];

            fH = [generatedConsonantsDir '\' mora '.dgv'];
            fname_joint = [dirJoint '\' mora '.joint'];

            disp(mora)
            H = loadBin(fH, 'float', 26);
            S = loadBin(fS, 'float', 19);
% log
fprintf(flog, '%s:\t', mora);
fprintf(flog, 'gesture,%4d\t', size(H, 2));
fprintf(flog, 'speech,%4d\t', size(S, 2));
            
            % make joint vector
            %   with scep0, gesture->speech
            J = makeJoint(H, S, 1, 0);
            frameJ = size(J, 2);
% log
fprintf(flog, 'joint,%4d\n', frameJ);
            
            fjoint = fopen(fname_joint, 'wb');
            for ii = 1:frameJ
                fwrite(fjoint, J(:, ii), 'float');
            end
            fclose(fjoint);
        end % nV2
    end % nFP
    fclose(flog);
    clear flog
    
%% using recorded data
elseif TYPE == 1
    recordedDataDir = 'F:\H2SwithDelta\2ndTrain_byRecordedData\recordedData\dgvs';
    dirSv = 'F:\Japanese5vowels\scep18\1';
    dirSc = 'F:\JapaneseConsonants';
    dirJoint = 'F:\H2SwithDelta\2ndTrain_byRecordedData\jointHS';
    
    logfile = [dirJoint '\frameNum_jointHS.txt'];
    flog = fopen(logfile, 'wt');

    for nFP = 1:8 % the first phoneme
        for nV2 = 1:5 % the vowel follows the first phoneme
            if nFP > 5
               mora = [firstPhoneme(nFP) vowel(nV2)];
               fS = [dirSc '\' firstPhoneme(nFP) '\suzuki\16k\scep18\1\' mora '.scep'];
            else % vowels
               mora = [firstPhoneme(nFP) vowel(nV2)];
               fS = [dirSv '\' mora '.scep'];
            end
            fH = [recordedDataDir '\' mora '.dgvs'];
            fname_joint = [dirJoint '\' mora '.joint'];

            disp(mora)
            H = loadBin(fH, 'uchar', 26);
            S = loadBin(fS, 'float', 19);
% log
fprintf(flog, '%s:\t', mora);
fprintf(flog, 'gesture,%4d\t', size(H, 2));
fprintf(flog, 'speech,%4d\t', size(S, 2));
            
            % make joint vector
            %   with scep0, gesture->speech
            J = makeJoint(H, S, 1, 0);
            frameJ = size(J, 2);
% log
fprintf(flog, 'joint,%4d\n', frameJ);
            
            fjoint = fopen(fname_joint, 'wb');
            for ii = 1:frameJ
                fwrite(fjoint, J(:, ii), 'float');
            end
            fclose(fjoint);
        end % nV2
    end % nFP
    fclose(flog);
    clear flog
end % TYPE
